version: '3.8'
services:
  # api:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   command: uvicorn api_rest_siat_soap.main:app --host ${APP_HOST} --port ${APP_PORT}
  #   environment:
  #       SIAT_TOKEN: ${SIAT_TOKEN}
  #       SIAT_ENVIRONMENT: ${SIAT_ENVIRONMENT}
  #       SYNC_OBJ: ${SYNC_OBJ}
  #       SP_SIAT_SYNC_OBJ_TIMEOUT: ${SP_SIAT_SYNC_OBJ_TIMEOUT}
  #       NIT: ${NIT}
  #       SP_SIAT_SYSTEM_CODE: ${SP_SIAT_SYSTEM_CODE}
  #       SP_SIAT_LOG_LEVEL: ${SP_SIAT_LOG_LEVEL}
  #       SP_SIAT_SOAP_REQUEST_TIMEOUT: ${SP_SIAT_SOAP_REQUEST_TIMEOUT}
  #       KEY_PASSWORD: ${KEY_PASSWORD}
  #       POETRY_VERSION: ${POETRY_VERSION}
  #       APP_HOST: ${APP_HOST}
  #       APP_PORT: ${APP_PORT}
  #       ENVIRONMENT: ${ENVIRONMENT}
  #   volumes:
  #     - ${PWD}/../../:/workspace
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}
  #   env_file:
  #     - '../.env'
  #   depends_on:
  #     - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - "mongodb-data:/data/db"
    env_file:
      - '../.env'
volumes:
  mongodb-data: {}
